# Generated by Django 5.2.6 on 2025-09-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrefacultad', models.CharField(max_length=100)),
                ('cod_facultad', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('is_active', models.CharField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='facultad_fotos/')),
            ],
        ),
    ]
