# Generated by Django 5.2.6 on 2025-10-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_ubicacion_faculty_ubicación_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecarrera', models.CharField(max_length=100)),
                ('cod_facultad', models.CharField(max_length=20)),
                ('duracion_años', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
    ]
