# Generated by Django 5.2.6 on 2025-10-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_carrera_alter_faculty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Carreras', to='server.faculty'),
        ),
    ]
