# Generated by Django 5.2.6 on 2025-10-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_carrera_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pagina/static/facultad_fotos/'),
        ),
    ]
