# Generated by Django 5.2.6 on 2025-10-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_faculty_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreestudiante', models.CharField(max_length=100)),
                ('cod_estudiante', models.CharField(max_length=20)),
                ('email', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
