# Generated by Django 5.2.6 on 2025-10-06 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_inscriccion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
