# Generated by Django 5.2.6 on 2025-10-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_estudiante_fecha_inscriccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estudiantes', to='server.carrera'),
        ),
    ]
