# Generated by Django 5.2.6 on 2025-10-06 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='Carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='server.carrera'),
        ),
    ]
