# Generated by Django 5.2.6 on 2025-10-06 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_materia_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programar_Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Esta activa la programacion?')),
                ('fecha_programación', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programar', to='server.estudiante')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programar', to='server.materia')),
            ],
            options={
                'verbose_name': 'Programar materias',
                'verbose_name_plural': 'Programar materias',
                'unique_together': {('student', 'subject', 'fecha_programación')},
            },
        ),
    ]
