# Generated by Django 5.2.6 on 2025-10-06 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_programar_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programar_materia',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programar_student', to='server.estudiante'),
        ),
        migrations.AlterField(
            model_name='programar_materia',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programar_subject', to='server.materia'),
        ),
    ]
